### ISSUE TITLE
Database fatal error when index.cnxml.html is not valid xml or if there's no text

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-archive#199]
This is a bug in plxslt which we use in the index_fulltext trigger on the module_files table when the filename is index.cnxml.html.

The bug has been filed with plxslt: https://github.com/petere/plxslt/issues/2

We're probably going to fix this in cnx-archive by using python and lxml instead of plxslt.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
