### ISSUE TITLE
initdb has SQL permissions issue

### ISSUE THREAD

**Issue by rich-hart** [openstax/cnx-archive#304]
Related to issue https://github.com/Connexions/cnx-publishing/issues/49

**Comment by rich-hart** [comment]
I've added some notes on how to approach fixing this bug here: https://github.com/Connexions/cnx-archive/compare/sql_permissions_v2

**Comment by pumazi** [comment]
See also, Connexions/cnx-deploy#267

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
