### ISSUE TITLE
DuckDuckGo result with content_info route

### ISSUE THREAD

**Issue by pumazi** [openstax/cnx-archive#305]
It appears that the DuckDuckGo.com results for 'intro to physics' contains a route that produces a `404 Not Found`. We maybe need to generalize the redirection route?

In this case the url for the result is `http://cnx.org/content/col11553/1.1/content_info`. It's also a derived copy of physics, but that's a different issue.

**Comment by reedstrm** [comment]
Hrmmph. Those where valid URLs before the move to legacy.cnx.org. Not sure where we're sending those now. I'l ltake a look.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
