### ISSUE TITLE
activate_venv enhancements

### ISSUE THREAD

**Issue by rich-hart** [openstax/cnx-archive#374]
Improvements to connecting our sql database to our python virtualenv. 

PR #373 
- Add a comment to say that we ported the code from virtualenv activate_this.py
- Test whether we're using virtualenv first
  - if the database is remote, raise an exception
  - if the database is local, create the activate venv function
- Factor the activate venv function creation code into a db helper function
- runtime check in activate venv

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
