### ISSUE TITLE
upgrade DB to 9.4 (or 9.5?)

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-archive#418]
Current production runs on 9.3. There are significant new capabilities (around json, mostly) that we'd like to use that are 9.4 (or 9.5, for jsonb) specific.  This raises some issues. Is the current code 9.3 clean? The default postgresql install on new machines is currently 9.4. Is there coded needed to enable such a migration, or is it purely an operational issue?

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
