### ISSUE TITLE
Search composite modules

### ISSUE THREAD

**Issue by karenc** [openstax/cnx-archive#425]
Composite modules are currently excluded from search:

https://github.com/Connexions/cnx-archive/pull/424#discussion_r59663427

**Comment by reedstrm** [comment]
While they are excluded from full-site search, they do show up in in-book search. I have a cunning plan to make the whole-site search more book-aware, involving leveraging the full-text machinery better to match books when content in them matches. This will end up matching composite module text as part of the book.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
