### ISSUE TITLE
dbinit deprecation leaves out example dataset

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-archive#471]
This warning: 'Deprecation warning: This script is going to be removed. ' doesn't mention the issue that cnx-db init does not currently include the example data set loaded vi cnx-archive-initdb --with-example-data
Perhaps that shoud become cnx-archive-example-data , or just instructions for using the SQL dump in the tests/data folder.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
