### ISSUE TITLE
Deal with frontend caches

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-archive#515]
Archive is designed to be mostly cache-deterministic: URLs fall into static classes of cachability.  Most URLs are designed to never change what they deliver, once they deliver something other than a 404 (cache-forever). Certain URLs (/*extras) are designed to be short-cached - they may change, usually not rapidly, but consistently. We have recently added a two new classes of URL: one  is intended to long-cache, but may have one, significant change early in it's life: new, to-be-baked content. If a to-be-baked page is fetched before it has completed baking, we want to short-cache that content. Once it has baked, we want to long-cache. This transition (short to long) can be handled by making the cache-control headers on the content-archive URLs depend on the baked state - raw (or in process) should be classed as short-cache. Once they bake, the next refresh will have their appropriate long-cache value.

Unfortunately, if we have content that changes baked status by virtue of a non-content change (stale recipe) and so needs a rebake, we need to somehow trigger the cache to purge those now stale values.

I'm not sure if that needs to be handled here, in archive,  or in publish.

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
