### ISSUE TITLE
Fail gracefully when dependent services are offline

### ISSUE THREAD

**Issue by philschatz** [openstax/cnx-archive#518]
Related to https://github.com/Connexions/oer.exports/pull/2978

Failure to convert TeX to MathML needs to be a fatal error for baking - right now it retries twice and skips the conversion - should be an error, reporting a usable error message, that ends up in the monitoring page.

**Comment by karenc** [comment]
Another failure we should consider is invalid xml.

We use lxml to fix invalid xml without reporting errors:

```python
def _sanitize_xml(raw_xml):
    """Wraps the XML and sanitizes the namespaces."""
    xml_parser = etree.XMLParser(ns_clean=True, recover=True)
    elms = lxml.html.fragments_fromstring(raw_xml)
    # If the raw_xml starts with untagged content, it will be parsed
    # to a string rather than an Element instance.
    # Thus causing etree.tostring to error unless we first check its type.
    raw_xml = ''.join([
        utf8(isinstance(e, (str, bytes,)) and e or etree.tostring(e))
        for e in elms])
    xml = etree.fromstring(XML_WRAPPER.format(raw_xml), xml_parser)
    result = utf8(etree.tostring(xml))
    result = result[result.find('>')+1:result.rfind('<')].strip()
    return result
```

https://github.com/Connexions/cnx-epub/blob/c572a9be22bf175955e75c202e110cb52ae8a0c9/cnxepub/models.py#L88

We might want to see if it's necessary or maybe have an option to use `recover=False`

See https://github.com/Connexions/cnx-epub/pull/126

**Comment by philschatz** [comment]
[\[Trello Story about XHTML parsing\]](https://trello.com/c/m5ihYVoC/71-ctepipeline104a-modify-the-epub-pipeline-so-that-the-output-for-each-step-is-html-parseable-xhtml-change-cnxml-html-to-output-xh)

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
