### ISSUE TITLE
extending xpath api to full archive search

### ISSUE THREAD

**Issue by reedstrm** [openstax/cnx-archive#533]
We deployed a  partial `xpath` search solution, that allows searching within a specific book, in 4b0af0346fc3b78bc5946977a7f5f4f9ee9ab178 This uses urls like this:
    `https://archive.cnx.org/xpath.{html,json}?id=<uuid@ver>&q=<xpath>`

The desire is to extend this to work without the id, to search the entire repository.

I'd like to suggest two changes to have this be more in keeping with existing content retrieval, extra info, and  search. For those three, we have a pattern:
  `https://site/<verb>[/optional content_hash*][.optional return type]?verb_specific_params`

 *(note that content hash contains a lot of subcases involving shortIds, presence or absence of a book 
context, and/or versions of the book and/or page  - most of those redirect to the canonical long uuid@version forms)

The strongest parallel for `xpath` being fullsite and in-book `search` - `xpath` is a special case of search, clearly. There, the searches  are:
  `https://archive/search?q=my search terms[&query_type={AND|OR|weakAND}]`
and:
   `https://archive/search/<content_hash>q=my search terms[&query_type={AND|OR}]`

Similarly, the extra info api does:
  `https://archive/extras[content_hash]`
The no hash version returns site wide extra info, with hash provides extra info about that content.

(In this context, the  difference between what's direct metadata under `/contents` and what is under `/extras` has to do with if it can change without a publish event happening for that specific piece of content)
 
Content can be fetched from four api end points `contents`, `resources`, and `exports`, and `specials`.

As to return type, the one other case that allows for such selection is `contents`: we do not provide a HTML versions of `search` or `extras` (or `resources` or `exports` or `specials`) . 
Content fetch follows this pattern: 
   `https://archive/contents/content_hash[.{json|html}][/content title]`
Default return type depends on `Accepts:` header in request. Note the extension is on the content, not the verb. I'd suggest for xpath that we make it a param, `return_type` since there isn't an result object to attach it to. If we attach it to the hash (or to the lack of hash) it looks like we're searching a different document. I guess I'd be ok w/ putting it on the id (or if no id, on the verb) if it's made optional, defaulting to `json`

So, I'd like to see for xpath:
`https://archive/xpath[content_hash]?q=xpath[&return_type={json|html}]`

The two changes are: content hash os part of path, not a param, return type is a param, not part of path.

This lays out where there are holes in our other APIs, as well: what should /contents (w/ no id) return? What about extras and optional titles?

**Comment by philschatz** [comment]
yep, sounds good overall. Just one note: other content uses `[.{json|html}]` to describe the return type (and decides it based on Accept headers if no extension is given. 

Extending that, it seems like the XPath query should use the same method, rather than a `return_type={json|html}`

**Comment by reedstrm** [comment]
>Default return type depends on Accepts: header in request. Note the extension is on the content, not the verb. I'd suggest for xpath that we make it a param, return_type since there isn't an result object to attach it to. If we attach it to the hash (or to the lack of hash) it looks like we're searching a different document. I guess I'd be ok w/ putting it on the id (or if no id, on the verb) if it's made optional, defaulting to json

Yes, that's what I said. Though if you look at the generated urls, they seem a bit odd:

`/xpath.html?q=whatever`

**Comment by philschatz** [comment]
Good point on the extension problem. I think that the primary user of this API will be QA. Having a list-of-links in HTML would make it easy for them to test. 

If the API returns HTML when `Accept: text/html` is sent by a browser, a developer can just send an XPath query that shows all the content that needs to be tested and QA can just open each link in a new tab.

**Comment by kerwinso** [comment]
@philschatz The original intention behind the ability to search archive for specific markup was that the Content Team would be able to use it as well. When Cade was here this summer, we sat down with him to develop documentation for this SQL query that he wrote: https://github.com/caderitter/xpath-book-search

If we intend this API to replace Cade's query, I'd hope we could work with a CM to develop similar documentation and make sure this tool meets their need as well. Lack of product owner input is one of the reasons that this extension is currently unusable. Refer to [this comment](https://github.com/Rhaptos/cnx-tools/pull/1#issuecomment-328958616) for more details.

cc @openstaxalina

**Comment by brittweinstein** [comment]
CLOSING. If this presents itself as an issue again, we will reopen.
