### ISSUE TITLE
Use Module mimetype to identify type

### ISSUE THREAD

**Issue by edwoodward** [openstax/cnx-archive#630]
An earlier fix used the "m" in the module id to identify it as a module. The mimetype should be used.

**Comment by edwoodward** [comment]
TESTING - The only way to test is to confirm that module PDFs are not available for download.

**Comment by omehes** [comment]
verified on qa - pdf is removed from Downloads/Page section

**Comment by omehes** [comment]
reverified. fixed
staging.cnx.org

{"date": "2019-02-19 10:33:39 CST",
"webview": "6fea2e99064f4522c968ac6b4ada6203d9eb9e5d (v0.46.0)",
"cnx-archive": "4.10.0",
"cnx-publishing": "0.15.0",
"oer.exports": "bomb.blondie v0.72.0",
"press": "8.0.2",
"cnx-deploy": "v2.37.1"
}
